var questions = [
		{
			"img":"https://i.loli.net/2018/11/21/5bf4cb9c2dfbc.gif",
			"anwser1":"这个是酒吧里闪动的灯光",
			"anwser2":"这仅仅是一个带有三角形的球体不断闪动",
			"anwser3":"这是一个无颜色的演唱会的聚光灯"
		},
		{
			"img":"https://i.loli.net/2018/11/21/5bf4cce47f917.gif",
			"anwser1":"这是一个从天空俯视的陆地动态的界面",
			"anwser2":"这给我一种黑暗起伏的飞机光球的错觉",
			"anwser3":"这就是一个会动的旋转中的球体"
		},
		{
			"img":"https://i.loli.net/2018/11/21/5bf4cf69b4d45.gif",
			"anwser1":"如果小时候有自动生成积木，我可以省下几百元",
			"anwser2":"如果小时候有这个，我可以省下几十元",
			"anwser3":"如果小时候有这个，我也不喜欢玩积木"
		},
		{
			"img":"https://i.loli.net/2018/11/21/5bf4d109d2ab2.gif",
			"anwser1":"记得小时候我对掌机非常热爱，花了不少钱",
			"anwser2":"我小的时候不是很热爱掌机",
			"anwser3":"我是女生，更喜欢一些女生玩的东西，例如镜子"
		},
		{
			"img":"https://i.loli.net/2018/11/21/5bf4eaa8db028.gif",
			"anwser1":"我会为看到类似的《纪念碑谷》中的形状和剧情购买关卡",
			"anwser2":"我只是觉得这很神奇，并不会购买关卡看更多",
			"anwser3":"我觉得这很普通"
		},
]
